config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks

  namespace :admin do
    resources :tasks
  end
  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title,:description,:score, presence: true
  belongs_to :user

  scope :recent, -> { order("created_at DESC")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :tasks

    def admin?
      is_admin
    end 
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < ApplicationController

  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required

  def index
    @tasks = Task.all.recent.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to admin_task_path
    else
      render :new
    end
  end

  def show
    @task = Tasl.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end


   def destroy
     @task = Task.find(params[:id])
     @task.destroy
     redirect_to admin_task_path
   end

  private

  def task_params
    params.require(:task).permit(:title, :description, :score)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def admin_required
   if !current_user.admin?
     redirect_to "/", alert: "You are not admin."
   end
 end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create, :update, :destroy]
  before_action :find_task_and_check_permission, only: [:edit, :update, :destroy]
  def index
    @tasks = Task.all.recent.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    if @task.save
    redirect_to tasks_path
  else
    render :new
  end
end

  def show
    @task = Task.find(params[:id])

  end

  def edit

  end

  def update

    if @task.update(task_params)
    redirect_to tasks_path
  else
    render :edit
   end
  end

  def destroy


    @task.destroy
    redirect_to tasks_path, alert: "删除成功"
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :score)
  end

  def find_task_and_check_permission
    @task = Task.find(params[:id])

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "欢迎来到第九块"
  end
end

app/helpers/admin/tasks_helper.rb
module Admin::TasksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/tasks/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>编辑任务</h2>
    <hr>
  <%= simple_form_for @task do |f| %>
    <div class="form-group">
      <%= f.input :title, input_html: { class: "form-control"} %>
      <%= f.input :description, input_html: { class: "form-control"} %>
      <%= f.input :score, input_html: { class: "form-control"} %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
  <% end %>

app/views/admin/tasks/index.html.erb
<div class="col-md-12">
  <div class="task">
    <%= link_to("新增任务", new_admin_task_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>发布时间</th>
        <th>任务</th>
        <th>叙述</th>
        <th>创建者</th>
        <th>得分</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.created_at %></td>
          <td><%= link_to(task.title, task_path(task)) %>

            <div class="pull-right">
              <%= link_to("Edit", edit_admin_task_path(task), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", task_path(task), class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
            </div>

          </td>
          <td><%= simple_format(task.description) %></td>

          <td><%= task.user.email %></td>
          <td><%= task.score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <span class="pull-right">
     <span>
        <% sum = 0 %>
        <% @tasks.each do |task| %>
        <% %>
        <% sum = sum + task.score %>
        <% end %>
        <h4>总计 <%= sum %> 分</h4>
     </span>
  </span>

  <div class="text-center">
    <%= will_paginate @tasks %>
  </div>
</div>

app/views/admin/tasks/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新增讨论版</h2>

    <hr>
    <%= form_for @task do |f| %>

    标题
    <%= f.text_field :title %>
    <br>
    叙述
    <br>
    <%= f.text_area :description %>
    <br>

    <%= f.submit "Submit", :disable_with => 'Submitting...' %>
    <% end %>

</div>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2018
       <a href="http://da4d89a3.wiz03.com/share/s/3qjoCz22wkv72dFHr51JKiOo0-7Cl40esQyz2iNvmv38ne_4" target=_new>DJK</a>
        <br>Design by chang
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">第九块</a>
            <ul class="nav navbar-nav">
             <li class="active">
               <%= link_to("任务", tasks_path) %>
             </li>
           </ul>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                  <li><%= link_to("登录", new_user_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <% if current_user.admin? %>
                       <li>
                         <%= link_to("Admin 选单", admin_tasks_path ) %>
                       </li>
                     <% end %>
                        <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JDstore 后台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "common/navbar" %>
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
          <li> <%= link_to("task", admin_tasks_path) %> </li>
        </ul>
      </div>
      <div class="col-md-10">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quota</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <%= yield %>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
    <%= f.input :score, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/tasks/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>编辑任务</h2>

    <hr>

    <%= render "form" %>

</div>

app/views/tasks/index.html.erb
<div class="col-md-12">
  <div class="task">
    <%= link_to("新增任务", new_task_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>发布时间</th>
        <th>任务</th>
        <th>叙述</th>
        <th>创建者</th>
        <th>扣分项</th>
        <th>加分项</th>
        <th>得分</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.created_at %></td>
          <td><%= link_to(task.title, task_path(task)) %>
             <% if current_user && current_user == task.user %>
            <div class="pull-right">
              <%= link_to("Edit", edit_task_path(task), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", task_path(task),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
            </div>
          <% end %>
          </td>
          <td><%= simple_format(task.description) %></td>
          </td>
          <td><%= task.user.email %></td>
          <td>  <%= link_to("Edit", edit_task_path(task), class: "btn btn-sm btn-default")%></td>
          <td>  </td>
          <td><%= task.score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
    <div class="text-center">
      <%= will_paginate @tasks %>
    </div>

</div>

app/views/tasks/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新增任务</h2>

    <hr>
    <%= render "form" %>
</div>

app/views/tasks/show.html.erb
<div class="col-md-12">
  <div class="task">
    <% if current_user && current_user == @task.user %>

    <%= link_to("编辑", edit_task_path(@task), class: "btn btn-info pull-right")%>
    <% end %>
  </div>
  <h2><%= @task.title %></h2>
  <hr>
  <p><%= @task.description %></p>
  <hr>
  <h4><td><%= @task.score %></td></h4>

</div>

app/views/welcome/index.html.erb
<h1>你好，世界！</h1>